# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('azimuth', models.FloatField()),
                ('zenith', models.FloatField()),
            ],
        ),
    ]
