# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='camera_type',
            field=models.CharField(default='thermal', max_length=20),
            preserve_default=False,
        ),
    ]
